image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip3 install torch numpy nltk 
    command: pwd
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
